
name: ALI

on:
  workflow_dispatch:

jobs:
  UPLOAD:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2.3.4
#      - name: Install Aria2
#        run: |
#          sudo apt install aria2
#          aria2c "https://chirmyram-my.sharepoint.com/personal/ani_chirmyram_top/_layouts/15/download.aspx?UniqueId=e033e88d-3845-4281-8c54-2e13c85343bf&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvY2hpcm15cmFtLW15LnNoYXJlcG9pbnQuY29tQDNjNTJlNTgwLTQzZTgtNGU3Yy1hOGI4LTNjMzBhNjM3ZWVhYSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2NjI2MjQxMzciLCJleHAiOiIxNjYyNjI3NzM3IiwiZW5kcG9pbnR1cmwiOiJMZ0UvUmZGNUxEMTRrZ3ZWRlM0d3V0M3ZtRnJxekp1V2I2WEFIYzZQdWp3PSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTUwIiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJObUkxTnpFME56SXRaV0UxTVMwME0yWmhMVGsxWWpVdFlXTTFaVFE0TnpKbU16aGgiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWlRJMk5XUmhOelV0TVRZNE1TMDBNekJrTFdJek9UY3RNMkl6WmpKbE9USm1OV0prIiwiYXBwX2Rpc3BsYXluYW1lIjoib25laW5kZXgiLCJmYW1pbHlfbmFtZSI6ImFuaSIsImFwcGlkIjoiZmRlYWJmMTQtZmI0MS00NTM3LWFkOWMtYTE1YWU0ZjMxOGQ4IiwidGlkIjoiM2M1MmU1ODAtNDNlOC00ZTdjLWE4YjgtM2MzMGE2MzdlZWFhIiwidXBuIjoiYW5pQGNoaXJteXJhbS50b3AiLCJwdWlkIjoiMTAwMzIwMDEyQ0VFNTM0MyIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAxMmNlZTUzNDNAbGl2ZS5jb20iLCJzY3AiOiJteWZpbGVzLnJlYWQgYWxsZmlsZXMucmVhZCBteWZpbGVzLndyaXRlIGFsbGZpbGVzLndyaXRlIGFsbHNpdGVzLnJlYWQgYWxsc2l0ZXMud3JpdGUgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjIwLjE5MC4xNDQuMTcxIn0.czhyUUcxU0lYZXBwOS9CbFRRVVVDUFo3UnlMMGxKcTF1NmVSWUxnZFgvND0&ApiVersion=2.0"
#          aria2c "https://chirmyram-my.sharepoint.com/personal/ani_chirmyram_top/_layouts/15/download.aspx?UniqueId=1475fc9a-f463-4ae3-9878-9adc42707932&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvY2hpcm15cmFtLW15LnNoYXJlcG9pbnQuY29tQDNjNTJlNTgwLTQzZTgtNGU3Yy1hOGI4LTNjMzBhNjM3ZWVhYSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2NjI2MjQ0NTAiLCJleHAiOiIxNjYyNjI4MDUwIiwiZW5kcG9pbnR1cmwiOiJwQTFoMHZmeW1kTTdxTWxhSHd5YTJVVlpha2VSM2J2QzRZa2FNa2JYeFFZPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTUwIiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJaVEJrTldRNU5UWXRNalF6TmkwME5HVmtMV0ZtTldRdE1qRTBORGN5T0RRME16SXgiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWlRJMk5XUmhOelV0TVRZNE1TMDBNekJrTFdJek9UY3RNMkl6WmpKbE9USm1OV0prIiwiYXBwX2Rpc3BsYXluYW1lIjoib25laW5kZXgiLCJmYW1pbHlfbmFtZSI6ImFuaSIsImFwcGlkIjoiZmRlYWJmMTQtZmI0MS00NTM3LWFkOWMtYTE1YWU0ZjMxOGQ4IiwidGlkIjoiM2M1MmU1ODAtNDNlOC00ZTdjLWE4YjgtM2MzMGE2MzdlZWFhIiwidXBuIjoiYW5pQGNoaXJteXJhbS50b3AiLCJwdWlkIjoiMTAwMzIwMDEyQ0VFNTM0MyIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAxMmNlZTUzNDNAbGl2ZS5jb20iLCJzY3AiOiJteWZpbGVzLnJlYWQgYWxsZmlsZXMucmVhZCBteWZpbGVzLndyaXRlIGFsbGZpbGVzLndyaXRlIGFsbHNpdGVzLnJlYWQgYWxsc2l0ZXMud3JpdGUgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjIwLjE5MC4xNDQuMTY5In0.YjYxZnpZa1IyTm96dlhLVXk1VHAveXB5bGxOb0ViRWVBVDNReXF0Z1BZcz0&ApiVersion=2.0"
#      - name: Telegram Notify
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          video: ./*.mkv
      - name: Set Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          echo "${{ secrets.RCLONE_CONF }}" > rclone.conf
          mkdir -p /home/runner/.config/rclone/
          chmod 777 /home/runner/.config/rclone/
          mv $GITHUB_WORKSPACE/rclone.conf /home/runner/.config/rclone/
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
#        if: env.SSH_ACTIONS == 'true'
        with:
          mode: ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: ap
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

